Adding Matrix

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[1,2,3],[11,12,13]])
result = np.add(a,b)
print(result)

[[ 5  7  9]
 [ 5  7  9]
 [18 20 22]]


In [3]:
print(a + b)

[[ 5  7  9]
 [ 5  7  9]
 [18 20 22]]


Subtract

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[1,2,3],[11,12,13]])
result = np.subtract(a,b)
print(result)

[[-3 -3 -3]
 [ 3  3  3]
 [-4 -4 -4]]


In [5]:
print(a - b)

[[-3 -3 -3]
 [ 3  3  3]
 [-4 -4 -4]]
