In [1]:
import numpy as np

In [7]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [8]:
arr = np.array(x)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [10]:
arr.sum(axis =0)

array([12,  8,  9])

In [13]:
arr.sum(axis=1)

array([ 6, 15,  8])