Array Creation: Conversion from other python structures


In [6]:
import numpy as np

In [7]:
list_array = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(list_array)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [8]:
print(list_array.shape)
print(list_array.dtype)
print(list_array.size)

(3, 3)
int32
9


In [9]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [10]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
zeros.shape

(2, 5)

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
lspace = np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [16]:
lspace1 = np.linspace(1,50,10)
print(lspace1)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [17]:
lspace3 = np.linspace(1,5,4)
print(lspace3)

[1.         2.33333333 3.66666667 5.        ]


In [19]:
emp = np.empty((4,6))
print(emp)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56599128e-307
  1.29060531e-306 8.45599366e-307]
 [7.56593017e-307 1.11258854e-306 1.11261502e-306 1.42410839e-306
  7.56597770e-307 6.23059726e-307]
 [1.42419530e-306 7.56602523e-307 1.29061821e-306 1.37961234e-306
  9.34598926e-307 1.33511562e-306]
 [9.34600963e-307 8.45559303e-307 9.45697982e-308 1.33511562e-306
  8.90103560e-307 1.42410974e-306]]


In [21]:
emp_like = np.empty_like(1)
print(emp_like)

544433568


In [23]:
ide = np.identity(45)
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [25]:
ide.shape

(45, 45)

In [26]:
arr = np.arange(99)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])