In [1]:
import numpy as np

In [7]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [8]:
arr = np.array(x)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [10]:
arr.sum(axis =0)

array([12,  8,  9])

In [13]:
arr.sum(axis=1)

array([ 6, 15,  8])

# to transform row to column and column to row we use ( T )

In [14]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [16]:
arr.flat

In [18]:
for item in arr:
    print(item)

[1 2 3]
[4 5 6]
[7 1 0]


In [19]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


# for finding dimension

In [21]:
arr.ndim

2

# for minimum maximum and sorting (indexing wise)

In [23]:
one = np.array([1,3,4,634,2])

In [25]:
one.argmax()

3

In [26]:
one.argmin()

0

In [27]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)