Array Creation: Conversion from other python structures


In [3]:
import numpy as np

In [4]:
list_array = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(list_array)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [5]:
print(list_array.shape)
print(list_array.dtype)
print(list_array.size)

(3, 3)
int32
9
