Array Creation: Conversion from other python structures


In [6]:
import numpy as np

In [7]:
list_array = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(list_array)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [8]:
print(list_array.shape)
print(list_array.dtype)
print(list_array.size)

(3, 3)
int32
9


In [9]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [10]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
zeros.shape

(2, 5)

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
lspace = np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [16]:
lspace1 = np.linspace(1,50,10)
print(lspace1)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [17]:
lspace3 = np.linspace(1,5,4)
print(lspace3)

[1.         2.33333333 3.66666667 5.        ]
