Array Creation: Conversion from other python structures


In [4]:
import numpy as np

In [5]:
list_array = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(list_array)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [6]:
print(list_array.shape)
print(list_array.dtype)
print(list_array.size)

(3, 3)
int32
9


In [7]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [8]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
zeros.shape

(2, 5)

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])