What is NumPy

NumPy stands for numeric python which is a python package for thecomputation and processing of the multidimensional and singledimensional array elements.

In [ ]:
import numpy as np

In [29]:
myarr = np.array([3,6,37,7])
print(myarr)
print(myarr[0])
print(myarr.shape)
print(myarr.dtype)

[ 3  6 37  7]
3
(4,)
int32


In [ ]:
myarr[0,1]

In [ ]:
myarr1 = np.array([[3,6,37,7]])
print(myarr1[0,1])
myarr1[0]




In [ ]:
print(myarr1.shape)
print(myarr1.dtype)

In [ ]:
myarr1[0,1] = 45
myarr1

Array Creation: Conversion from other python structures

In [28]:
list_array = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(list_array)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [30]:
print(list_array.shape)
print(list_array.dtype)
print(list_array.size)

(3, 3)
int32
9
