Write a NumPy program to multiply two given matrices.

In [1]:
import numpy as np

In [3]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[9,8,7],[4,5,6],[3,5,6]])

multiply = np.dot(matrix_1, matrix_2)
print(multiply)

[[ 26  33  37]
 [ 74  87  94]
 [122 141 151]]


In [8]:
matrix_1 = np.array([1, 2, 3], [4, 5, 6])
matrix_2 = np.array([9, 8, 7], [4, 5, 6])
result = np.array([matrix_1, matrix_2])

print(result)


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [11]:
matrix_1 = np.array([[1, 2], [4, 5]])
matrix_2 = np.array([[9, 8], [4, 5]])
result = np.dot(matrix_1, matrix_2)
print(result)


[[17 18]
 [56 57]]
