Write a NumPy program to multiply two given matrices.

In [1]:
import numpy as np

In [3]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[9,8,7],[4,5,6],[3,5,6]])

multiply = np.dot(matrix_1, matrix_2)
print(multiply)

[[ 26  33  37]
 [ 74  87  94]
 [122 141 151]]


In [ ]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[9,8,7],[4,5,6],[3,5,6]])

