Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.



In [1]:
import numpy as np

In [9]:
x = np.random.uniform(0,99,(5,5))
print(x)

[[64.65085541 25.92497988 24.39305844 70.11592003  7.62980387]
 [45.73183635 97.72899102 54.39814376  8.31986018 87.2205239 ]
 [81.3508459  78.18333587 29.85780597 52.27703466 63.52618457]
 [45.0678579  73.16976033 37.21588361 92.91228134 85.33201851]
 [64.43553654 25.85068304 34.76857871 10.77133499 82.99456317]]
