In [ ]:
import numpy as np

In [ ]:
l = [i for i in range(1000)]
print(l)

In [ ]:
n_arr = np.arange(1000)
print(n_arr)

In [ ]:
print(n_arr.itemsize)   #size of each element in numpy array

In [ ]:
print(n_arr.size)    # size of array ==> total elements in numpy array

In [ ]:
print(n_arr.itemsize*n_arr.size)

In [ ]:
import sys

In [ ]:
a = 4 
print(sys.getsizeof(a))

In [11]:
print(sys.getsizeof(a)*len(l))

28000


In [13]:
a = [10,20,30]
b = np.array(a)

In [14]:
print(b)

[10 20 30]


In [15]:
print(type(b))

<class 'numpy.ndarray'>


in numpy array all the elements are of same type

In [18]:
x = [1, 2, 3, 5.46, 6.47]
y = np.array(x)
print(y)

[1.   2.   3.   5.46 6.47]


In [20]:
y = np.array(x, dtype=int)
print(y)

[1 2 3 5 6]
